baseurl             = "http://blog.donkeysharp.xyz"
builddrafts         = false
canonifyurls        = true
contentdir          = "content"
languageCode        = "es"
defaultContentLanguage = "es"
layoutdir           = "layouts"
publishdir          = "public"
theme               = "cocoa"
author              = "Donkeysharp"
title               = "Donkeysharp - Blog Personal"
pygmentsuseclasses  = true
# disqusshortname     = "donkeysharp_blog" # Comment out to disable Disqus.
pluralizelisttitles = false
googleAnalytics     = "UA-123-45"
enableEmoji         = true

[permalinks]
blog  = "blog/:slug/"

[[menu.main]]
name                   = "{ Blog }"
weight                 = -120
identifier             = "blog"
url                    = "/blog/"

[params]
include_rss            = true                          # include RSS <link> tag in <head> and show RSS icon
latestpostscount       = 5                             # how many posts to display on the home page
i18n_flags             = true                          # whether to display small country flags for available translations
author                 = "Sergio Guillen Mantilla"
cachebuster            = true                          # add the current unix timestamp in query string for cache busting css assets
dateform               = "Jan 2, 2006"
dateformfull           = "Mon Jan 2 2006 15:04:05 MST"
description            = "Don't panic"
email                  = ""
extracssfiles          = [ "/css/override.css" ]       # In your `static` directory, add/remove files as necessary.
faviconfile            = "img/leaf.ico"
github                 = "//github.com/donkeysharp"
instagram              = "//instagram.com/donkeysharp"
lang                   = "es"
noshowreadtime         = true                         # if true, don't show "<x> minutes read" in posts
selfintro              = ""                            # appears in the site header when set to a non-empty string
twitter                = "//twitter.com/donkeysharp"

highlightjs            = true
# highlightjslanguages = ["go"]                        # additional languages not included in the "common" set
# highlightjsStyle     = "darcula"


avatar                 = "img/donkeysharp.png" # path to image in static dir e.g img/avatar.png (do not use in the same time as gravatar)
# gravatar             = ""                # gravatar hash. see https://en.gravatar.com/site/implement/hash/. do not use in the same time as avatar

# The following are DEPRECATED.
gatracker              = "XYZ" # use googleAnalytics instead
initials               = "ad"  # displayed on single post page; deprecated in v0.3.0.
